lexik_jwt_authentication:
    secret_key: "MIIFHDBOBgkqhkiG9w0BBQ0wQTApBgkqhkiG9w0BBQwwHAQItyNrxvxPIAkCAggA
MAwGCCqGSIb3DQIJBQAwFAYIKoZIhvcNAwcECMr0x+6tVdMYBIIEyPx5rHO4YryR
qDWa1DPMYgA0yhk5EbDUKDqxUgVcOZ56B9073FTv2hDz2h22kIYOjW5yaL0T9RnL
JvfN3g3flzbefcMn02CZwP74L+UPmP1GvR/kAKMdcBHXQg0AhKdHNHeYINwQ4YK8
H0pF8Vdb+KqZLRM/Ub52gSJpTzdr/fHVmbIIRskbuMHB0OLzk5tNkTJ/BgaVhARg
FpoT8lmnQrUJQAFKW1NfB19M9JXIx1VkS87WzZVcyyNMva0Bh1thXCiDnhOTLnx3
mXyl+fPTMTUf/j3SJQndDIvxTTg3kXHXkjVu2kwN4v/B1U8jHSrSuuSegfZzdHhA
054a1Y3R3B9rx7Ar+CAQOyEUsP0hXT0pZptrCE8ESX8MbE4Ky9SoYSIc3XyIUAj3
gM9cfLym4BBfWApJD0cbxEknLL3SefAt/NkVWrIq/pRnRQuh5cpVa/3zDeb3eeGo
HNBR2wNCsqTcQ6erQWDgo19/2jbqAECPAJnjz3m/HzuulDvw/Jw+cKMM8CsOL+XL
KTFbkiEE4TBI1Pb/j1eM1kkBwR5ji1KER/6vSjOVAxP0XU331RMrHUGqOGDpXuUv
QRuz4eLUnggptVfX1781mYDLu7CYGxmM5uUwHM0shaEGSTM6WyM0wMxDyRy9pg3M
4mprqb0BnTiyfTX7AQboTwTCTM0nt8QHJ8mV5cjIvIXFxM5HfJrlYzmgMP+GTeUl
jw2eARgPZBloq7dxBwtpG6eH6Rccu2clPZeYWYOvn+qjkmEk+Lva5X+k/BfX4spY
fyIZc222ZCOexs/UcZAT4MGnHCXGvERwAmNGES2jPyWv9LYH5j16CanotzFP7ftW
PVfnJK7Ee07t+tTglJXkhSx+Og8yNAtmg4FYtDBV0XqYtOSXjDQDwmtvrjzf13ZF
4dyFLzZcSf1+FVOVPSO1Kfkh+NgngH3NR8OlyXmkmMPobg0hbdvesfHa9GiufDwx
Qzq2aTRsGbynMQsT3/hIpmWZcNpIm4C8Vsng+CBXA09ngo1c0QbxdGnon0i3DP/x
S7f2/vln3IS/vbrxDVcvQ2UEMIXum1frNXzSHOIjKxIhhxRxPrAFdZ603W41tKsA
dzKBwtYIafNB4u5XofT7SkNK+mAh4+DdISHqjHVHPmTiXSOjo8uD67ky38djHK9S
9Ddn+pqcBjxU2yNL4c9dJePQ0KqY/8a6X958MZJBx+ZQ/GotjLkGGHxz7DSciTH8
Qvv0Bya39fq3TLJYoGMufMsEdtrhJnYLXYcfaEvdFfgzzdv3pKPRHCGg5KtfMaKY
Qb6YtzWMSlIrSkRyYEMAjiVj9Eq5JrZAm3aV3W2iOyNuYO5400hdqEwB2PtC7v+k
wQ9f2cLb1JnPeIlWvF+O7AWK8TPM4zGvHrg4QX+3d/xuKTXxbUtL2ywrdhqWKpMA
S3SZjmDbDXpmH42tOQDAjm4OKnRCowkNqer+m1zdVc4fGuxqf2DsWPuN98aBVhwR
NnL5PlxuG3UKIMpUk2Ofl3RhjE+4joWxYpg7XJOaX057Te5LpAF2KRhrct9McgpO
c+jLOR+RkVDvohQASY5cPVJ8btE3N0F2mOPf1+Vsj1IRsICxCqXjzctCpuEHL8Tg
Pdi56Rz24TFk2ur0da03xA=="
    public_key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7hgSOGXUcSlwJyeJCBzU
gxEYUSYiiqXZcWEalfuEwN1C5rpnR9lSRENjiPRQdZgOLscwF8yzlQLhy6RlbGYA
EvuQkWg+f13rLKblHDv7X0ex1xw9VMO8/b++Rs+Xarcg6MKv/17aB3YqSAbOH2kj
Rg9ULa/kxS6pQE42FiB5pwTQK4SiREBu1tpX1DmdttWa4qsntSgW8paU4dxoq27G
wKvnfPzqsKD06mKl08iDEfXHLfiiTtO7mJ1jkHLN/2DXO6dMDWg3iTiiCpDzGwnp
8lFuuU4lNBG71/NL4o2oRnjEeD3FcwB/FNP/H4vhqQA/cY4qpJVt8NoUAag/yw/j
lQIDAQAB"
    pass_phrase: "9a0df5352e98533e2c67539e96ff33fe733414113ebd1520d37a53efae3afb87"
    token_ttl: 86400